### ISSUE TITLE
Must add --override-filter "" to command line, or fails to run

### ISSUE THREAD

**Issue by xcsdm** [myOmikron/mailcow-ldap-sync#10]
Using the command:
`./bin/python3 ./mailcow_ldap_sync/main.py --update-only-on-change-by-ldap --override-filter ""`
works exactly as expected.

Using only:
`./bin/python3 ./mailcow_ldap_sync/main.py --update-only-on-change-by-ldap`
results in an error:

`Traceback (most recent call last):
  File "./mailcow_ldap_sync/main.py", line 331, in <module>
    main(config, session, change_only_by_ldap=args.change)
  File "./mailcow_ldap_sync/main.py", line 41, in main
    first_name = user_params[conf['ldap']['user_mapping']['firstname']][0].decode('utf-8')
KeyError: 'givenName'`

**Comment by myOmikron** [comment]
Good catch
