### ISSUE TITLE
question: Is there a way to only synch the password once

### ISSUE THREAD

**Issue by theoneandonly-vector** [myOmikron/mailcow-ldap-sync#12]
I have technical passwords in the background so all users only connect their devices using app-passwords and normally just rely on sogo with SSO.
so I would like to only synch the pw once so a re-sync most likely wont kill my sessions anmyore and I would be able to use the technical pw to do email-migration with external tools (to also migrate all the calendars etc.)
this way I can fix the problems all at once..

**Comment by myOmikron** [comment]
I don't exactly understand what you are referring to with "technical passwords".

**Comment by theoneandonly-vector** [comment]
passwords which are unknown to the user

**Comment by myOmikron** [comment]
Closing as this is not the scope of this project
