### ISSUE TITLE
allow self-signed certificate on Mailcow-Host

### ISSUE THREAD

**Issue by theoneandonly-vector** [myOmikron/mailcow-ldap-sync#16]
This Option would allow me to generate the users and migrate their Data before I stop the old Mailserver

**Comment by myOmikron** [comment]
So you want an option, where you can specify a path to an additional CA?

**Comment by theoneandonly-vector** [comment]
that would be an option,yes but I think the easieast option would be to disable the CA-verification temporarily for the first synch
