### ISSUE TITLE
How can it work?

### ISSUE THREAD

**Issue by pkejval** [myOmikron/mailcow-ldap-sync#20]
Does anyone uses this? How can it work? As I know you cannot get user password from LDAP in userPassword attribute. (Windows Server 2022).

**Comment by ne0YT** [comment]
I use it with Univention Corporate Server -> works.
But as I have SSO on SoGo I actually don't really need the pw.. but it's working with the pw too for SMTP/IMAP clients.

**Comment by myOmikron** [comment]
I am using slapd, that gives the `userPassword` when requesting with an admin account (or allowing it for an other account). Maybe Windows AD doesn't provide the password at all?

**Comment by pkejval** [comment]
Thanks for answers. I'll try to figure something out. 😂

11. 5. 2023 14:10:09 myOmikron ***@***.***>:

**Comment by myOmikron** [comment]
I'm closing this, as it seems not be be an issue of this project
