### ISSUE TITLE
Microsoft Active Directory compatibility

### ISSUE THREAD

**Issue by twstagg** [myOmikron/mailcow-ldap-sync#4]
Is there a way I could make this work with Active Directory? 

I just spent the last 24 hours failing at configuring https://github.com/Programmierus/ldap-mailcow properly - there are some things that I could not get fully working (IMAP login for one...)

I think https://github.com/Programmierus/ldap-mailcow is a good start - I just could not for the life of me get Dovecot/IMAP login working with this setup. Has anyone gotten this working with Active DIrectory? I would like to see configuration examples if it is usable!

I am running into a roadblock with mailcow-ldap-sync in which it is not possible to configure the userPassword attribute as it is not used in Microsoft Active Directory in the same way you interact with OpenLDAP attribute of the same name. I do not need live logins to persist, I am OK with a utility that will periodically sync user information according to the "ldap" users returned from my Active Directory

**Comment by myOmikron** [comment]
For requests regarding other repositories, use their issues and don't hijack other repos.

If you could explain how the hash of the user can be retrieved, I can build you a version of the script using that method.

**Comment by twstagg** [comment]
@myOmikron I am not making a request for the other repository - I have given up on using it as it appears to be abandoned & is not working as intended (at least currently)

I was trying to use your project to get some sort of synchronization between mailcow -> AD - I understand the limitation now.

I guess I am unsure whether or not AD supports retrieving password hashes at all. Perhaps I should move over to OpenLDAP or another directory service that supports this...
