### ISSUE TITLE
Add Option to only update a specific user

### ISSUE THREAD

**Issue by theoneandonly-vector** [myOmikron/mailcow-ldap-sync#9]
I would love to sync only a specific user when defined wiht a parameter

**Comment by myOmikron** [comment]
How to want to provide this "filter"? 

There are several ways this could be archived:
- Specifying the `user_filter` (already an option in your `config.json`)
- Provide an additional filter per cli e.g.: `--override-filter <filter_string>`
- Another option would be to use regex based matching, but I really don't think this is really a use case

**Comment by theoneandonly-vector** [comment]
something like the 2nd option would be great. so I can easily pass my user with a variable from outside

**Comment by theoneandonly-vector** [comment]
hey there..

I just tried the user_filter method..

but it just deletes all the non-matching users.. so only the user which matches will be kept.. what can I do to only UPDATE this one user but keep all the others..
